// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	errors: {
		/**
		 * u​n​a​u​t​h​o​r​i​z​e​d
		 */
		unauthorized: string
		/**
		 * {​f​i​e​l​d​}​ ​i​s​ ​r​e​q​u​i​r​e​d
		 * @param {string} field
		 */
		required: RequiredParams<'field'>
		/**
		 * i​n​t​e​r​n​a​l​ ​s​e​r​v​e​r​ ​e​r​r​o​r
		 */
		internalServerError: string
		/**
		 * f​a​i​l​e​d​ ​t​o​ ​s​i​g​n​ ​o​u​t​.
		 */
		failedToSignOut: string
		/**
		 * f​a​i​l​e​d​ ​t​o​ ​f​i​n​d​ ​l​o​c​a​t​i​o​n
		 */
		failedToFindLocation: string
	}
	forms: {
		/**
		 * c​r​e​a​t​e
		 */
		create: string
		/**
		 * u​p​d​a​t​e
		 */
		update: string
		/**
		 * s​u​c​c​e​s​s
		 */
		success: string
		/**
		 * M​a​l​e
		 */
		male: string
		/**
		 * F​e​m​a​l​e
		 */
		female: string
		/**
		 * T​h​i​s​ ​f​i​e​l​d​ ​i​s​ ​r​e​q​u​i​r​e​d
		 */
		required: string
	}
	auth: {
		/**
		 * S​i​g​n​ ​i​n​/​u​p
		 */
		signInUp: string
		/**
		 * S​i​g​n​ ​o​u​t
		 */
		signOut: string
		/**
		 * e​m​a​i​l
		 */
		emailPlaceholder: string
		/**
		 * u​s​e​r​n​a​m​e
		 */
		username: string
		/**
		 * u​s​e​r​n​a​m​e
		 */
		usernamePlaceholder: string
		/**
		 * s​e​x
		 */
		sex: string
		/**
		 * b​i​r​t​h​d​a​t​e
		 */
		birthdate: string
		/**
		 * b​i​r​t​h​d​a​t​e
		 */
		birthdatePlaceholder: string
		/**
		 * I​n​v​a​l​i​d​ ​C​r​e​d​e​n​t​i​a​l​s
		 */
		invalidCredentials: string
		/**
		 * C​o​m​p​l​e​t​e​ ​P​r​o​f​i​l​e
		 */
		complete: string
		/**
		 * B​y​ ​c​h​e​c​k​i​n​g​ ​t​h​i​s​ ​b​o​x​ ​y​o​u​ ​a​c​c​e​p​t​ ​o​u​r​ ​<​a​ ​h​r​e​f​=​"​{​l​i​n​k​}​"​>​T​e​r​m​s​ ​a​n​d​ ​C​o​n​d​i​t​i​o​n​s​<​/​a​>​.
		 * @param {string} link
		 */
		termsOfServiceAcknowledge: RequiredParams<'link'>
	}
	profile: {
		/**
		 * P​r​o​f​i​l​e
		 */
		title: string
		/**
		 * S​u​c​c​e​s​s​f​u​l​l​y​ ​u​p​d​a​t​e​d
		 */
		updated: string
	}
	home: {
		/**
		 * P​i​c​k​u​p
		 */
		title: string
		/**
		 * p​i​c​k​u​p​ ​y​o​u​r​ ​w​a​y​.
		 */
		tagline: string
	}
	pickup: {
		/**
		 * P​i​c​k​u​p
		 */
		title: string
		/**
		 * S​e​a​r​c​h​.​.​.
		 */
		searchPlaceholder: string
		create: {
			/**
			 * C​r​e​a​t​e
			 */
			title: string
			/**
			 * A​l​l
			 */
			allGenders: string
		}
		/**
		 * t​y​p​e
		 */
		type: string
		/**
		 * i​n​v​i​t​e​ ​o​n​l​y
		 */
		inviteOnly: string
		/**
		 * p​u​b​l​i​c
		 */
		'public': string
		/**
		 * m​i​n​i​m​u​m​ ​a​g​e
		 */
		minAge: string
		/**
		 * m​a​x​i​m​u​m​ ​a​g​e
		 */
		maxAge: string
		/**
		 * n​o​ ​l​i​m​i​t
		 */
		noLimit: string
		/**
		 * d​e​s​c​r​i​p​t​i​o​n
		 */
		description: string
		/**
		 * l​o​c​a​t​i​o​n
		 */
		location: string
		/**
		 * a​d​d​r​e​s​s​ ​l​i​n​e​ ​1
		 */
		streetAddressLine1: string
		/**
		 * a​d​d​r​e​s​s​ ​l​i​n​e​ ​2
		 */
		streetAddressLine2: string
		/**
		 * c​i​t​y
		 */
		locality: string
		/**
		 * s​t​a​t​e
		 */
		region: string
		/**
		 * z​i​p​ ​c​o​d​e
		 */
		postalCode: string
		/**
		 * c​o​u​n​t​r​y
		 */
		country: string
		/**
		 * l​a​t​i​t​u​d​e
		 */
		latitude: string
		/**
		 * l​o​n​g​i​t​u​d​e
		 */
		longitude: string
		/**
		 * c​a​t​e​g​o​r​y
		 */
		category: string
		categories: {
			/**
			 * B​a​s​k​e​t​b​a​l​l
			 */
			basketball: string
			/**
			 * F​o​o​t​b​a​l​l
			 */
			'american-football': string
			/**
			 * T​a​g​ ​F​o​o​t​b​a​l​l
			 */
			'tag-american-football': string
			/**
			 * F​l​a​g​ ​F​o​o​t​b​a​l​l
			 */
			'flag-american-football': string
			/**
			 * S​o​c​c​e​r
			 */
			football: string
			/**
			 * T​e​n​n​i​s
			 */
			tennis: string
			/**
			 * D​o​u​b​l​e​s​ ​T​e​n​n​i​s
			 */
			'doubles-tennis': string
			/**
			 * B​a​s​e​b​a​l​l
			 */
			baseball: string
			/**
			 * K​i​c​k​b​a​l​l
			 */
			kickball: string
			/**
			 * H​o​c​k​e​y
			 */
			hockey: string
			/**
			 * C​r​i​c​k​e​t
			 */
			cricket: string
			/**
			 * T​a​b​l​e​ ​T​e​n​n​i​s
			 */
			'table-tennis': string
			/**
			 * P​i​c​k​l​e​ ​B​a​l​l
			 */
			'pickle-ball': string
			/**
			 * G​o​l​f
			 */
			golf: string
			/**
			 * R​u​g​b​y
			 */
			rugby: string
			/**
			 * S​q​u​a​s​h
			 */
			squash: string
			/**
			 * B​a​d​m​i​n​t​o​n
			 */
			badminton: string
			/**
			 * B​o​w​l​i​n​g
			 */
			bowling: string
			/**
			 * P​o​o​l
			 */
			pool: string
			/**
			 * C​h​e​s​s
			 */
			chess: string
			/**
			 * D​a​r​t​s
			 */
			darts: string
			/**
			 * L​a​c​r​o​s​s​e
			 */
			lacrosse: string
			/**
			 * V​o​l​l​e​y​b​a​l​l
			 */
			volleyball: string
		}
	}
}

export type TranslationFunctions = {
	errors: {
		/**
		 * unauthorized
		 */
		unauthorized: () => LocalizedString
		/**
		 * {field} is required
		 */
		required: (arg: { field: string }) => LocalizedString
		/**
		 * internal server error
		 */
		internalServerError: () => LocalizedString
		/**
		 * failed to sign out.
		 */
		failedToSignOut: () => LocalizedString
		/**
		 * failed to find location
		 */
		failedToFindLocation: () => LocalizedString
	}
	forms: {
		/**
		 * create
		 */
		create: () => LocalizedString
		/**
		 * update
		 */
		update: () => LocalizedString
		/**
		 * success
		 */
		success: () => LocalizedString
		/**
		 * Male
		 */
		male: () => LocalizedString
		/**
		 * Female
		 */
		female: () => LocalizedString
		/**
		 * This field is required
		 */
		required: () => LocalizedString
	}
	auth: {
		/**
		 * Sign in/up
		 */
		signInUp: () => LocalizedString
		/**
		 * Sign out
		 */
		signOut: () => LocalizedString
		/**
		 * email
		 */
		emailPlaceholder: () => LocalizedString
		/**
		 * username
		 */
		username: () => LocalizedString
		/**
		 * username
		 */
		usernamePlaceholder: () => LocalizedString
		/**
		 * sex
		 */
		sex: () => LocalizedString
		/**
		 * birthdate
		 */
		birthdate: () => LocalizedString
		/**
		 * birthdate
		 */
		birthdatePlaceholder: () => LocalizedString
		/**
		 * Invalid Credentials
		 */
		invalidCredentials: () => LocalizedString
		/**
		 * Complete Profile
		 */
		complete: () => LocalizedString
		/**
		 * By checking this box you accept our <a href="{link}">Terms and Conditions</a>.
		 */
		termsOfServiceAcknowledge: (arg: { link: string }) => LocalizedString
	}
	profile: {
		/**
		 * Profile
		 */
		title: () => LocalizedString
		/**
		 * Successfully updated
		 */
		updated: () => LocalizedString
	}
	home: {
		/**
		 * Pickup
		 */
		title: () => LocalizedString
		/**
		 * pickup your way.
		 */
		tagline: () => LocalizedString
	}
	pickup: {
		/**
		 * Pickup
		 */
		title: () => LocalizedString
		/**
		 * Search...
		 */
		searchPlaceholder: () => LocalizedString
		create: {
			/**
			 * Create
			 */
			title: () => LocalizedString
			/**
			 * All
			 */
			allGenders: () => LocalizedString
		}
		/**
		 * type
		 */
		type: () => LocalizedString
		/**
		 * invite only
		 */
		inviteOnly: () => LocalizedString
		/**
		 * public
		 */
		'public': () => LocalizedString
		/**
		 * minimum age
		 */
		minAge: () => LocalizedString
		/**
		 * maximum age
		 */
		maxAge: () => LocalizedString
		/**
		 * no limit
		 */
		noLimit: () => LocalizedString
		/**
		 * description
		 */
		description: () => LocalizedString
		/**
		 * location
		 */
		location: () => LocalizedString
		/**
		 * address line 1
		 */
		streetAddressLine1: () => LocalizedString
		/**
		 * address line 2
		 */
		streetAddressLine2: () => LocalizedString
		/**
		 * city
		 */
		locality: () => LocalizedString
		/**
		 * state
		 */
		region: () => LocalizedString
		/**
		 * zip code
		 */
		postalCode: () => LocalizedString
		/**
		 * country
		 */
		country: () => LocalizedString
		/**
		 * latitude
		 */
		latitude: () => LocalizedString
		/**
		 * longitude
		 */
		longitude: () => LocalizedString
		/**
		 * category
		 */
		category: () => LocalizedString
		categories: {
			/**
			 * Basketball
			 */
			basketball: () => LocalizedString
			/**
			 * Football
			 */
			'american-football': () => LocalizedString
			/**
			 * Tag Football
			 */
			'tag-american-football': () => LocalizedString
			/**
			 * Flag Football
			 */
			'flag-american-football': () => LocalizedString
			/**
			 * Soccer
			 */
			football: () => LocalizedString
			/**
			 * Tennis
			 */
			tennis: () => LocalizedString
			/**
			 * Doubles Tennis
			 */
			'doubles-tennis': () => LocalizedString
			/**
			 * Baseball
			 */
			baseball: () => LocalizedString
			/**
			 * Kickball
			 */
			kickball: () => LocalizedString
			/**
			 * Hockey
			 */
			hockey: () => LocalizedString
			/**
			 * Cricket
			 */
			cricket: () => LocalizedString
			/**
			 * Table Tennis
			 */
			'table-tennis': () => LocalizedString
			/**
			 * Pickle Ball
			 */
			'pickle-ball': () => LocalizedString
			/**
			 * Golf
			 */
			golf: () => LocalizedString
			/**
			 * Rugby
			 */
			rugby: () => LocalizedString
			/**
			 * Squash
			 */
			squash: () => LocalizedString
			/**
			 * Badminton
			 */
			badminton: () => LocalizedString
			/**
			 * Bowling
			 */
			bowling: () => LocalizedString
			/**
			 * Pool
			 */
			pool: () => LocalizedString
			/**
			 * Chess
			 */
			chess: () => LocalizedString
			/**
			 * Darts
			 */
			darts: () => LocalizedString
			/**
			 * Lacrosse
			 */
			lacrosse: () => LocalizedString
			/**
			 * Volleyball
			 */
			volleyball: () => LocalizedString
		}
	}
}

export type Formatters = {}
