/* tslint:disable */
/* eslint-disable */
/**
 * Pickup API
 * Pickup API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaceFeature
 */
export interface PlaceFeature {
    /**
     * 
     * @type {Date}
     * @memberof PlaceFeature
     */
    created_at: Date;
    /**
     * 
     * @type {number}
     * @memberof PlaceFeature
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof PlaceFeature
     */
    latitude: number;
    /**
     * 
     * @type {string}
     * @memberof PlaceFeature
     */
    location_type: string;
    /**
     * 
     * @type {number}
     * @memberof PlaceFeature
     */
    longitude: number;
    /**
     * 
     * @type {number}
     * @memberof PlaceFeature
     */
    place_id: number;
    /**
     * 
     * @type {string}
     * @memberof PlaceFeature
     */
    type: string;
    /**
     * 
     * @type {Date}
     * @memberof PlaceFeature
     */
    updated_at: Date;
}

/**
 * Check if a given object implements the PlaceFeature interface.
 */
export function instanceOfPlaceFeature(value: object): boolean {
    if (!('created_at' in value)) return false;
    if (!('id' in value)) return false;
    if (!('latitude' in value)) return false;
    if (!('location_type' in value)) return false;
    if (!('longitude' in value)) return false;
    if (!('place_id' in value)) return false;
    if (!('type' in value)) return false;
    if (!('updated_at' in value)) return false;
    return true;
}

export function PlaceFeatureFromJSON(json: any): PlaceFeature {
    return PlaceFeatureFromJSONTyped(json, false);
}

export function PlaceFeatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceFeature {
    if (json == null) {
        return json;
    }
    return {
        
        'created_at': (new Date(json['created_at'])),
        'id': json['id'],
        'latitude': json['latitude'],
        'location_type': json['location_type'],
        'longitude': json['longitude'],
        'place_id': json['place_id'],
        'type': json['type'],
        'updated_at': (new Date(json['updated_at'])),
    };
}

export function PlaceFeatureToJSON(value?: PlaceFeature | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'created_at': ((value['created_at']).toISOString()),
        'id': value['id'],
        'latitude': value['latitude'],
        'location_type': value['location_type'],
        'longitude': value['longitude'],
        'place_id': value['place_id'],
        'type': value['type'],
        'updated_at': ((value['updated_at']).toISOString()),
    };
}

