/* tslint:disable */
/* eslint-disable */
/**
 * Pickup API
 * Pickup API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: nathanfaucett@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    birthdate: Date;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    created_at: Date;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: string;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    sex: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    terms_of_service_acknowledge: boolean;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    updated_at: Date;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    username: string;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): boolean {
    if (!('birthdate' in value)) return false;
    if (!('created_at' in value)) return false;
    if (!('id' in value)) return false;
    if (!('sex' in value)) return false;
    if (!('terms_of_service_acknowledge' in value)) return false;
    if (!('updated_at' in value)) return false;
    if (!('username' in value)) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'birthdate': (new Date(json['birthdate'])),
        'created_at': (new Date(json['created_at'])),
        'email': json['email'] == null ? undefined : json['email'],
        'id': json['id'],
        'sex': json['sex'],
        'terms_of_service_acknowledge': json['terms_of_service_acknowledge'],
        'updated_at': (new Date(json['updated_at'])),
        'username': json['username'],
    };
}

export function UserToJSON(value?: User | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'birthdate': ((value['birthdate']).toISOString()),
        'created_at': ((value['created_at']).toISOString()),
        'email': value['email'],
        'id': value['id'],
        'sex': value['sex'],
        'terms_of_service_acknowledge': value['terms_of_service_acknowledge'],
        'updated_at': ((value['updated_at']).toISOString()),
        'username': value['username'],
    };
}

